### ISSUE TITLE
Comparing dict and ordereddict shouldn't show a type mismatch

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#107]
Comparing an ordereddict to a dict should only complain about the contents if they don't match, not the types. I think this might be done in pytest's assertion rewriting so we might not be able to control it

**Comment by Birne94** [comment]
Would it be sufficient to just swap the arguments of the `isinstance` call here?
https://github.com/taverntesting/tavern/blob/32e85d9cfd3b64b97a48cc0c667a7e4c8615e1ca/tavern/util/dict_util.py#L238

The actual type will most likely always be a basic type (str, float, int, bool, dict, list) since it originates from the yaml file. The response might be anything depending on the backend used.

**Comment by michaelboulton** [comment]
I decided to just make sure that the 'actual' type returned was a subclass of the 'expected', which as you said is going to be loaded directly from YAML
