### ISSUE TITLE
Using anchors and parametrize results in wrongly formatted request

### ISSUE THREAD

**Issue by fvarga** [taverntesting/tavern#157]
Hi,

I don't know if this is an issue or I'm just using it incorrectly, but I'm trying to parametrize a key in a reused request, it looks something like this:

~~~~
 marks:
  - parametrize: 
      key: tested_key
      vals:
        - val1
        - val2
        - val3

stages:
  - name: Stage 1

    request:
      <<: *request1
      json:
        <<: *request1_json
        "{tested_key}": "something" 
~~~~

val1, val2 and val3 are already present in the request1_json and I'm trying to replace one of them with different value for each test. 
Then I see the key in the formatted stage of the request twice:

~~~~
val1: something
'val1': something
~~~~

So I suspect there is some issue with formatting the request in this case.
Is this something that should be working? It would really help me simplify my tests.

**Comment by michaelboulton** [comment]
I don't think it should be formatting keys at all, so I'm not even sure how you got that result to be honest!

It is a minor change, but I don't think formatting keys will be supported in future because it brings up nondeterministic behaviour (on Python 2 and -3.5 at least). for example, this request:

```yaml
json:
  "{key_fmt}": 123
  abc: 456
```

if `key_fmt` is `"abc"`, then it's unknown as to which one will actually be sent in the request because when it iterates over the dictionary of keys to format, the order is undefined.

**Comment by fvarga** [comment]
@michaelboulton that's why I thought it could work with the reused request JSON, because I can do 

```
json: &json1
  abc: 123
```

```
json:
  <<: *
  abc: 456
```

and it will work just fine.
But yeah I can see that it's the only case where this would make sense while in all the other ones it wouldn't.

Thanks!
