### ISSUE TITLE
Global configuration keys are not documented

### ISSUE THREAD

**Issue by funkyfuture** [taverntesting/tavern#16]
as i'm currently seeking to solve #6, i noticed there is no documentation on the available global parameters. i'm still undecided for a generic approach as @michaelboulton [proposed](https://github.com/taverntesting/tavern/issues/6#issuecomment-345977191) or a specific approach (`tavern --baseurl service.example.org …`), which i'd consider more user-friendly and preferable if there are only a few global parameters.

overall, the docs don't explain the concept of global settings or any aspects of it.

**Comment by michaelboulton** [comment]
The reason I suggested the 'generic' approach is because there are actually no 'built in' parameters, a bit of a consequence of the way we were originally using this library internally (within one test we might be querying 3-4 domains).

I'll try to get around to updating the documentation sometime soon, but (as I'm sure you've probably seen by now) essentially global configuration parameters are just used as the 'base' configuration for every test, and can then be overridden per test by including extra files

**Comment by michaelboulton** [comment]
Global configuration is now more accurately documented at https://taverntesting.github.io/documentation
