### ISSUE TITLE
How match at least one array object?

### ISSUE THREAD

**Issue by alessandro308** [taverntesting/tavern#205]
I've a variable that returns an array of element like:
`{"data": [{"name": "hello"}, {"name": "morning"}, {"name": "goodnight"}]}`

My test has to check that at least one item of them has name "morning". It is possible in YAML or I have to write an external function?

**Comment by KPilnacek** [comment]
I'd use an external function but maybe the tavern authors know a way how to do it :-)

**Comment by cetanu** [comment]
Maybe this:

    response:
      strict: no
      body:
        data:
          - !anything

**Comment by michaelboulton** [comment]
There is a half-implemented way of doing this in https://github.com/taverntesting/tavern/pull/162 , but if you read the comments on it you can see that there are a few issues with the way strict key matching works so I don't want to merge it for the time being. I don't really have an ETA on when that functionality will be available for you because it is a bit of a complicated issue, unfortunately!

I am just going to close this issue because it is related to https://github.com/taverntesting/tavern/issues/133 and I want to keep any future discussion in that issue.
