### ISSUE TITLE
Is there any way to print the JSON response?

### ISSUE THREAD

**Issue by varayal** [taverntesting/tavern#270]
I'm just trying to get the whole JSON response after running the test for evaluating after execution.

Any thought about how to do it?

**Comment by varayal** [comment]
by the way, I tried with $ext and I got the following error

```
>   ???
E   tavern.util.exceptions.BadSchemaError: Couldn't load utils:test_function

<string>:1: BadSchemaError
```

➜  tree
.
├── includes.yaml
├── test_createOrder.tavern.yaml
└── tfunctions
    └── utils.py

```
      save:
        $ext:
          function: utils:test_function
```

```
# utils.py
def test_function(response):
    return {response.json()}
```

**Comment by srinivasgoud-n** [comment]
Please let me know which command you are using to run the tests

**Comment by varayal** [comment]
tavern-ci test_test01.tavern.yaml

**Comment by felipehernandez** [comment]
This may be caused by Tavern not finding your file. I got it solved by:
- Adding __init__.py to your tfunctions folder and running `PYTHONPATH=$PYTHONPATH:. py.test ./`
- Running PYTHONPATH=$PYTHONPATH:tfunctions py.test ./
This will add your py files to the Python Path and make them visible to Tavern

**Comment by michaelboulton** [comment]
https://tavern.readthedocs.io/en/latest/basics.html#after-every-response
