### ISSUE TITLE
Is is possible to assert timing (like a "finishes within")?

### ISSUE THREAD

**Issue by tommyjcarpenter** [taverntesting/tavern#361]
Is it possible to assert that a certain HTTP call returns within a certain period of time?

**Comment by michaelboulton** [comment]
There is no way to do this (at the moment). If you want to check the response times of requests you might be better better off using a tool designed to do performance testing though - because Tavern is written in Python there is going to be some overhead for every request which will slightly affect the performance.

**Comment by tommyjcarpenter** [comment]
Agreed RE python but I still think this would be valuable to set reasonable bounds (if a request is taking way too long, for example).

**Comment by michaelboulton** [comment]
Ah, I thought your question was about testing the time taken in some way - if you want to just make sure that a request finished within a certain time period you can use the `timeout` key: https://tavern.readthedocs.io/en/latest/http.html?highlight=timeout#timeout-on-requests

**Comment by tommyjcarpenter** [comment]
ack, sorry I missed that, thanks!

**Comment by tommyjcarpenter** [comment]
your interpretation of this is also possibly valuable too; then tavern gets closer to replacing apache bench for me (though, not yet, the parallelism is still an issue).
