### ISSUE TITLE
Kafka Plugin

### ISSUE THREAD

**Issue by dgrahn** [taverntesting/tavern#419]
I'd like to add support for Kafka.

It looks like I can do this by copying the MQTT plugin and modifying it to work with a python-kafka library. I just want to make sure that this is the appropriate process or if you would recommend something else.

**Comment by pouledodue** [comment]
can you do one for Pulsar?

**Comment by michaelboulton** [comment]
The MQTT one is probably the best one to take inspiration from, and if you do run into any issues I can try and help, but is is very unlikely to ever get merged into mainline Tavern because I don't have any experience with Kafka to maintain it in future.

If you do succeed in making one then I will happily put in the README and in the documentation page so that other people can use it though.
