### ISSUE TITLE
No handlers could be found for logger "tavern.core"

### ISSUE THREAD

**Issue by edvm** [taverntesting/tavern#44]
When excecuting `(env) @math:tavern $ tavern-ci minimal_test.tavern.yaml` an error is printed on console
and the test doesn't run.
Contents from `minimal_test.tavern.yaml` is the 'Simple test' from: https://taverntesting.github.io/examples
![tavern](https://user-images.githubusercontent.com/689275/36900161-eb6ffd94-1e00-11e8-9db9-59c61d910ac7.png)
I instaled tavern with: `pip install  tavern`

Error doesnt happen when using python3.6.

**Comment by michaelboulton** [comment]
The test should run, it just won't print anything because there is no logging set up by default (if you do `tavern-ci --help` it will print the logging options).

The warning is just something that comes up when using Python 2 - I'm not sure why it comes up, but if you do enable logging then it won't show that warning.
