### ISSUE TITLE
JSON formatting in form-data

### ISSUE THREAD

**Issue by karimi** [taverntesting/tavern#448]
I'm running into an issue with character escaping when using JSON in a multipart post request data field. I prefer this json to be kept in an external file but even it's giving me issues even in the body of test. 
```
data:
        metadata: {"name": "Mo", "age":115}
```
Above code escapes the curly braces resulting in two parameters in the request, `name=Mo` and `age=115`. 
Using `!raw` doesn't fix this issue and gives following error: 
```yaml.constructor.ConstructorError: expected a scalar node, but found mapping```

The only way I could fix this was to wrap the whole json in `' '` and use !raw (This turns the json into a sting, but for my purposes it's fine since I'm parsing it in my application):
```
data:
        metadata: !raw '{"name": "Mo", "age":115}'
```
Now trying to achieve same ting with an external json, seems impossible because I suppose it's not allowed to used multiple ! notations back to back?

Following code results in error:
```
data:
        metadata: !raw !str !include metadata.json
```
Error:
```
yaml.parser.ParserError: while parsing a block mapping
expected <block end>, but found '<tag>'
```

**Comment by michaelboulton** [comment]
As you pointed out, the only way to pass JSON as a raw string is to use the `!raw` tag after wrapping it in a string, because JSON is valid YAML, and any JSON objects are just parsed as YAML mappings which then causes that error you're seeing.

Not being able to use multiple type tokens back to back is a limitation in YAML (or, the Python library being used to parse the YAML) and there isn't really any way to 'fix' it in Tavern.
