### ISSUE TITLE
Calling an external function in a test exclusively

### ISSUE THREAD

**Issue by arkster** [taverntesting/tavern#500]
In my tests I'm calling a number of various api endpoints to do validations using Tavern. However one of the things that I need to also do is to get some data directly from storage such as a mysql db that I need for subsequent tests and I cannot find a way to do this. In addition to mysql, I may also need to call other CLI scripts to get information that I need to provide as input parameters to other API endpoints within the same Yaml. 
I have been testing and trying various ways to call an external function directly without using a 'request' in the yaml but that as I've found does not work. Is there a way for me to call an external function to get what I'm looking for without explicitly calling an API in the same test (i.e skipping the request call itself)? As mentioned, I will need to data returned using the external function to provide as input to a subsequent GET.

**Comment by michaelboulton** [comment]
There isn't a way to call an external function without also running a test, but you can use a _fixture_ with the `usefixtures` mark to do whatever you need to do before a test
- https://tavern.readthedocs.io/en/latest/basics.html#usefixtures
- https://docs.pytest.org/en/latest/fixture.html

**Comment by arkster** [comment]
Thanks for the reply. Is there a way for me to pass a parameter to the fixture? Normally in a sequence of tests, it's very common for us to pass parameters to functions that return results that are used in subsequent tests. For example this is a typical test sequence for us.

* Call the internal api to create a customer
* Query the db and create a customer channel using the userid above
* Use the channel id returned using the above in subsequent tests

The first step is easy since we're calling the api that returns a customer id. However I need to use that customer id to create a customer channel using sql which means I have to call an external function. If I were to use a fixture, I would need to pass in the customer id to it. I'm not sure if I can do this since the documentation indicates I cannot. Can you suggest of any workarounds?

**Comment by michaelboulton** [comment]
If you define a fixture with a certain name then Pytest will implicitly pass the result of that fixture to any functions (or other fixtures) which use it, I'm not entirely sure if that works in Tavern though because it does mess around with the Pytest internals a bit.

For calling the API in the first place - there isn't a way to run one Tavern test and use the results in subsequent tests, it's not really something it was ever designed to do. The best thing to do it define a fixture which calls the customer API manually (using requests or something similar) and creates the user id from it, then use the result of that fixture in the Tavern tests.
