### ISSUE TITLE
Is there a timeout Tavern uses when running test?

### ISSUE THREAD

**Issue by zhaoyi0113** [taverntesting/tavern#507]
When I added more than 50 tavern tests I can see there are randomly failed tests with below error:

```
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f758948c710>: Failed to establish a new connection: [Errno 111] Connection refused
```

It happens on different test so it is not an issue with the test case itself. It is more like a random connection errors happened during testing. I have checked my server log which looks very good. Is there anything Tavern uses during testing like http connection timeout?

**Comment by benhowes** [comment]
Unless you've set a timeout https://tavern.readthedocs.io/en/latest/http.html#timeout-on-requests then it wouldn't time out.

There's not a lot to work with here, but it does sound like your server may not be accepting new connections immediately after serving a previous request?

Or - are you running your tavern tests in parallel some how?

**Comment by zhaoyi0113** [comment]
No I am not running it in parallel. I am using the command `python -m pytest MY-TAVERN_TEST_FILE` to run the test case.
Does tavern use multiple threads to send requests to my server or single thread?

**Comment by michaelboulton** [comment]
Tavern only runs one test at a time unless you explicitly tell it to by using pytest-xdist. 

The 'connection refused' will not show up in your server logs because it happens below the application level - it is trying to make the connection, but the server side isn't accepting connections because the port is not open or something like that. I would just look at the server side and make sure it's not holding onto any open connections or something.
