### ISSUE TITLE
Support for multiple global config files

### ISSUE THREAD

**Issue by benhowes** [taverntesting/tavern#53]

**Comment by michaelboulton** [comment]
For example if we have a set of variables which are common to multiple environments and we don't want to include in every test. eg

`tavern-ci --tavern-global-cfg common.yaml test_urls.yaml`
`tavern-ci --tavern-global-cfg common.yaml local_docker_urls.yaml`
`tavern-ci --tavern-global-cfg common.yaml integration_urls.yaml`

Instead of having `!include common.yaml` in every test
