### ISSUE TITLE
Allow pyjwt>2 in setup.cfg

### ISSUE THREAD

**Issue by willsthompson** [taverntesting/tavern#697]
Is there anything preventing pyjwt>2 from being allowed in Tavern 1.x? i.e. simply changing the requirement to `pyjwt>=1.7.1`? I think the only breaking API changes in pyjwt 2.0 are [the various jwt.decode() parameters](https://pyjwt.readthedocs.io/en/2.0.1/changelog.html#id2), but it doesn't look like Tavern uses any of them explicitly.

**Comment by michaelboulton** [comment]
I have fixed this on the '2.0' branch here https://github.com/taverntesting/tavern/pull/659 but the change does mean that any tests which are not already passing the 'algorithm' parameter will fail, complaining about that parameter being missing. I also don't want to add a default algorithm because it might not be what the person is using and cause the tests to fail with a jwt verification error.

I will add a warning to the 1.x releases saying that it will break soon though.

**Comment by willsthompson** [comment]
All our tests work fine on the latest 2.0 alpha, so we will just upgrade early. Thanks for your help.
