### ISSUE TITLE
skipif mark can't utilize global python variables or vars returned by fixtures

### ISSUE THREAD

**Issue by JattMones** [taverntesting/tavern#703]
Hi, I believe this is a feature request for the `skipif` mark. 

### **Issue**
I'm trying out the `skipif` mark (see three code examples below), but the `eval()` function is only able to access vars stored in tavern.util.dict_util (ie. system environment variables and perhaps variables included in `!include` .yaml files). I tried `skipif: "global_python_var is True"` which uses a global var created in the conftest.py (also tried `skipif: "global_python_var in globals()"`). Additionally, I tried accessing variables returned from fixtures (also defined in the conftest.py) using the `skipif: '{var_name}'` format, but get the following error: 

**ERROR:tavern.util.dict_util:Key(s) not found in format: url**, with this output (I set all env_values to None):
```
{'tavern': 
   {'env_vars': 
      {'NVM_INC': None, 'LDFLAGS': None, 'TERM_PROGRAM': None, 'PYENV_ROOT': None, 'NVM_CD_FLAGS': None, 'TERM': None, 'SHELL': None, 'CPPFLAGS': None, 'TMPDIR': None, 'GOOGLE_APPLICATION_CREDENTIALS': None, 'VAULT_ADDR': None, 'TERM_PROGRAM_VERSION': None, 'TERM_SESSION_ID': None, 'PYENV_VERSION': None, 'NVM_DIR': None, 'USER': None, 'SSH_AUTH_SOCK': None, 'PYENV_DIR': None, 'VIRTUAL_ENV': None, 'PATH': None, 'LaunchInstanceID': None, 'PWD': None, 'LANG': None, 'PYENV_HOOK_PATH': None, 'XPC_FLAGS': None, 'XPC_SERVICE_NAME': None, 'HOME': None, 'SHLVL': None, 'PYTHONPATH': None, 'LOGNAME': None, 'NVM_BIN': None, 'SECURITYSESSIONID': None, '__CF_USER_TEXT_ENCODING': None }
   }
}
```

### **Request**
Could the eval function called by `skipif` access information just like the test that it is marking **and** the python global namespace? Additionally, utilizing skipif with external functions (ie. getting a function to return either "True" or "False", would also be a good alternative). My overall goal is to skip all tests if my basic health-check test failed following these steps:

### _My intended usage and test examples_
1. run healthcheck/base test
2. verify response with external function which will either create a global, or change an existing global created in conftest.py (returns True or False based on response)
3. Other tests are skipped if the `skipif eval()` finds that the global var == False. (Alternatively, skips if external function called in eval() returns `"False"`)

Here are the example code snippets I tried (located in test_name.tavern.yaml file):

```
marks:
  - skipif: "'healthcheck_failed' in globals()"
```

```
marks:
 - skipif: "'{autouse_session_fixture_returned_from_conftest}' is True"
```

```
marks:
 - skipif:
     - $ext:
       - function: "utils:return_true" 
```

**Comment by michaelboulton** [comment]
The problem with the first example is that there is no such thing as 'global python namespace' in Tavern, as the tests doesn't run from inside any Python file. conftest.py is just a file that is loaded by Pytest to load fixtures from which are then passed through to Tavern, Tavern has no idea what is contained in that file.

The second example unfortunately doesn't work because Pytest evaluates fixtures after the generation of tests which is where Tavern currently formats marks. It has to do this because otherwise you might have a load of tests marked something like `{format_variable}` instead of the mark you actually wanted.

The last one isn't really an option because the 'skipif' fixture functionality is controlled by Pytest and I don't really want to have to have to duplicate that behaviour inside Tavern.

For reference, I think the easiest way to do this is just define a function called something like `skip_if_bad_health_check` and use it like this:

```python
@pytest.fixture
def skip_if_bad_health_check():
	if service_is_bad():
		pytest.skip()
```
```yaml
marks:
  - usefixtures:
    - skip_if_bad_health_check
```

**Comment by michaelboulton** [comment]
Going to close this as the original issue is solved.
