### ISSUE TITLE
Built-in fixtures not documented

### ISSUE THREAD

**Issue by denisw** [taverntesting/tavern#709]
One example of the "Advanced Cookbook" hints at the existence of a `request` as a pytest fixture built into Tavern. It would be great to have documentation about all built-in pytest fixtures provided by Tavern.

**Comment by michaelboulton** [comment]
In the cookbook, the example is using the Pytest fixture `request`, and you have access to all the fixtures which Pytest provides. It might be a bit confusing because 'request' is actually the pytest request object, and is not related to a http request.

For reference, here are the builtin pytest fixtures: https://docs.pytest.org/en/6.2.x/fixture.html

**Comment by denisw** [comment]
Ah, yes I mistook `request` to be a Tavern-specific object. Thank you for the clarification!
