### ISSUE TITLE
How to hide Format variables values ​​in console when test is failed?

### ISSUE THREAD

**Issue by Hosstell** [taverntesting/tavern#757]
I have a problem. Tavern shows all my secret tokens when the test is failed. How can I hide it? 

All secret tokens is imported from tavern.env_vars.

**Comment by michaelboulton** [comment]
There isn't anyway way to stop tavern doing this because just about any part of the request or response could be 'secret', this is why most CI providers like github, gitlab, etc. will try to replace any secret values you define in them with stars. If you want to make sure that no secrets are printed in general, then the only option is to make your test logs private
