### ISSUE TITLE
Reference an anchor in another file

### ISSUE THREAD

**Issue by alexdlaird** [taverntesting/tavern#97]
I've tried doing this and it doesn't seem to work. If there is a way to do it, the documentation doesn't seem to make it clear—for large test suites, this effectively makes anchors useless if they can't be passed between files.

**Comment by cetanu** [comment]
I don't believe this is possible in the current/latest YAML spec

**Comment by alexdlaird** [comment]
Right, that's what I was wondering. If this sorcery is or would ever be a part of Tavern, as it'd be incredibly useful. I understand (unfortunately) it won't work right out of the box, just a suggestion.

**Comment by michaelboulton** [comment]
This was actually supported in an ancient version of Tavern before it got open sourced, when it did some horrible stuff to load all the included files and test files at once.

This isn't really possible any more because anchors are calculated before any files are included (http://yaml.org/spec/1.1/index.html#id859109), so you don't have the included files loaded at the point where you need the anchors.
